# Generated by Django 5.0.7 on 2024-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_url', models.URLField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
