# Generated by Django 5.0.7 on 2024-12-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='first_para',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='fourth_para',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='newspaper_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='newspaper_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='second_para',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='third_para',
            field=models.TextField(null=True),
        ),
    ]
