# Generated by Django 5.0.7 on 2024-12-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_heading_article_first_para_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Heading',
            field=models.CharField(default='Heading', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='first_para',
            field=models.TextField(default='First Paragraph'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fourth_para',
            field=models.TextField(default='Fourth paragraph'),
        ),
        migrations.AlterField(
            model_name='article',
            name='newspaper_email',
            field=models.CharField(default='Newspaper_contact', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='newspaper_name',
            field=models.CharField(default='Newspaper_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='second_para',
            field=models.TextField(default='Second paragraph'),
        ),
        migrations.AlterField(
            model_name='article',
            name='third_para',
            field=models.TextField(default='Third paragraph'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
