# Generated by Django 5.0.7 on 2024-12-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_article_heading_alter_article_first_para_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Heading',
            field=models.CharField(default='Heading', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='first_para',
            field=models.TextField(default='First Paragraph', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='fourth_para',
            field=models.TextField(default='Fourth paragraph', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='newspaper_email',
            field=models.CharField(default='Newspaper_contact', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='newspaper_name',
            field=models.CharField(default='Newspaper_name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='second_para',
            field=models.TextField(default='Second paragraph', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='third_para',
            field=models.TextField(default='Third paragraph', null=True),
        ),
    ]
