# Generated by Django 5.0.7 on 2024-12-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_heading_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='first_para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='fourth_para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='newspaper_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='newspaper_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='second_para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='third_para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
